'use client';

import { Suspense, useEffect, useState } from 'react';
import Link from 'next/link';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { AlertTriangle, CheckCircle2, Loader2 } from 'lucide-react';
import { AuthShell } from '@/components/auth/auth-shell';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Field } from '@/components/ui/misc';
import { useI18n } from '@/components/providers/locale-provider';
import { getRepository } from '@/lib/data';
import { getBrowserSupabase } from '@/lib/supabase/browser-client';

const schema = z
  .object({ password: z.string().min(8), confirmPassword: z.string().min(8) })
  .refine((v) => v.password === v.confirmPassword, {
    path: ['confirmPassword'],
    message: 'mismatch',
  });

type Values = z.infer<typeof schema>;

/**
 * Recovery links generated by `supabase.auth.admin.generateLink()` always
 * land with the session in the URL **hash** (`#access_token=...&type=
 * recovery`) — that format predates PKCE and there is no server-generated
 * equivalent of it, since PKCE needs a code_verifier the client must have
 * created *before* the request, which is impossible for a link nobody's
 * browser initiated.
 *
 * `@supabase/ssr`'s `createBrowserClient` hardcodes `flowType: 'pkce'`,
 * which — it turns out — does not just prefer PKCE, it disables the
 * implicit-grant hash parser entirely. Left to its own devices the client
 * misreads this exact hash as a broken PKCE callback and throws
 * `AuthPKCEGrantCodeExchangeError: Not a valid PKCE flow url`, silently, on
 * mount — no session is ever attached, and the "set new password" button
 * just fails with "Auth session missing!". So the hash is parsed and handed
 * to `setSession()` by hand here, bypassing the broken auto-detection.
 */
function parseRecoveryHash(hash: string): { access_token: string; refresh_token: string } | null {
  if (!hash) return null;
  const params = new URLSearchParams(hash.startsWith('#') ? hash.slice(1) : hash);
  const access_token = params.get('access_token');
  const refresh_token = params.get('refresh_token');
  if (!access_token || !refresh_token) return null;
  return { access_token, refresh_token };
}

type LinkState = 'checking' | 'ready' | 'invalid';

function ResetPasswordForm() {
  const { t, href } = useI18n();
  const [done, setDone] = useState(false);
  const [linkState, setLinkState] = useState<LinkState>('checking');
  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<Values>({
    resolver: zodResolver(schema),
    defaultValues: { password: '', confirmPassword: '' },
  });

  useEffect(() => {
    let cancelled = false;

    async function establish() {
      // Demo mode has no real auth session to attach — the form just
      // validates input, so there is nothing to wait for.
      if (getRepository().mode !== 'supabase') {
        if (!cancelled) setLinkState('ready');
        return;
      }
      const tokens = parseRecoveryHash(window.location.hash);
      if (!tokens) {
        if (!cancelled) setLinkState('invalid');
        return;
      }
      const { error } = await getBrowserSupabase().auth.setSession(tokens);
      if (cancelled) return;
      if (error) {
        setLinkState('invalid');
        return;
      }
      // The tokens are single-use bearer credentials; get them out of the
      // visible URL (and browser history) once they've done their job.
      window.history.replaceState(null, '', window.location.pathname + window.location.search);
      setLinkState('ready');
    }

    establish();
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <AuthShell
      title={t.auth.resetTitle}
      subtitle={t.auth.resetSubtitle}
      footer={
        <Link href={href('/sign-in')} className="font-medium text-accent hover:underline">
          {t.auth.backToSignIn}
        </Link>
      }
    >
      {linkState === 'checking' ? (
        <div className="flex items-center justify-center gap-3 py-8 text-sm text-ink-muted">
          <Loader2 className="size-4 animate-spin" aria-hidden />
          {t.auth.resetChecking}
        </div>
      ) : linkState === 'invalid' ? (
        <div className="flex flex-col gap-4">
          <div className="flex items-start gap-3 rounded-lg border border-danger/25 bg-danger/8 p-4">
            <AlertTriangle className="mt-0.5 size-5 shrink-0 text-danger" aria-hidden />
            <div>
              <p className="text-sm font-medium text-ink">{t.auth.resetInvalidTitle}</p>
              <p className="mt-1 text-sm text-ink-muted">{t.auth.resetInvalidBody}</p>
            </div>
          </div>
          <Button asChild size="lg">
            <Link href={href('/forgot-password')}>{t.auth.resetRequestNew}</Link>
          </Button>
        </div>
      ) : done ? (
        <div className="flex items-start gap-3 rounded-lg border border-success/25 bg-success/8 p-4">
          <CheckCircle2 className="mt-0.5 size-5 shrink-0 text-success" aria-hidden />
          <p className="text-sm text-ink">{t.common.saved}</p>
        </div>
      ) : (
        <form
          noValidate
          className="flex flex-col gap-4"
          onSubmit={handleSubmit(async (values) => {
            await getRepository().resetPassword('session', values.password);
            setDone(true);
          })}
        >
          <Field
            label={t.auth.password}
            htmlFor="password"
            hint={t.auth.passwordHint}
            error={errors.password ? t.auth.passwordHint : undefined}
          >
            <Input id="password" type="password" autoComplete="new-password" {...register('password')} />
          </Field>
          <Field
            label={t.auth.confirmPassword}
            htmlFor="confirmPassword"
            error={errors.confirmPassword ? t.auth.passwordMismatch : undefined}
          >
            <Input
              id="confirmPassword"
              type="password"
              autoComplete="new-password"
              {...register('confirmPassword')}
            />
          </Field>
          <Button type="submit" size="lg" disabled={isSubmitting}>
            {isSubmitting ? <Loader2 className="animate-spin" aria-hidden /> : null}
            {t.auth.setPassword}
          </Button>
        </form>
      )}
    </AuthShell>
  );
}

/**
 * No `useSearchParams()` any more (the token now arrives in the hash, which
 * only the browser ever sees), but the Suspense boundary stays: this page
 * still needs to render a static shell during the production build without
 * throwing on `window` access in `useEffect`, which only runs client-side.
 */
export default function ResetPasswordPage() {
  return (
    <Suspense>
      <ResetPasswordForm />
    </Suspense>
  );
}
