import {
  AlignLeft,
  BarChart3,
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  ChevronDown,
  CircleDot,
  CircleHelp,
  ClipboardCheck,
  Clock,
  Compass,
  FileText,
  FilePlus2,
  Gauge,
  Hash,
  Heading,
  Image as ImageIcon,
  Inbox,
  LayoutDashboard,
  Link as LinkIcon,
  ListChecks,
  Mail,
  MapPin,
  MessageSquareQuote,
  Minus,
  Palette,
  Paperclip,
  Phone,
  PieChart,
  Presentation,
  Rows3,
  SeparatorHorizontal,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SquareCheck,
  Star,
  Text,
  TrendingUp,
  Type,
  UserRound,
  Users,
  EyeOff,
  type LucideIcon,
} from 'lucide-react';

/**
 * A closed icon registry. Config objects reference icons by name, and this map
 * is the only place a name becomes a component — so tree-shaking still works
 * and a typo surfaces as a visible fallback rather than a crash.
 */
const REGISTRY: Record<string, LucideIcon> = {
  AlignLeft,
  BarChart3,
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  ChevronDown,
  CircleDot,
  CircleHelp,
  ClipboardCheck,
  Clock,
  Compass,
  FileText,
  FilePlus2,
  Gauge,
  Hash,
  Heading,
  Image: ImageIcon,
  Inbox,
  LayoutDashboard,
  Link: LinkIcon,
  ListChecks,
  Mail,
  MapPin,
  MessageSquareQuote,
  Minus,
  Palette,
  Paperclip,
  Phone,
  PieChart,
  Presentation,
  Rows3,
  SeparatorHorizontal,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SquareCheck,
  Star,
  Text,
  TrendingUp,
  Type,
  UserRound,
  Users,
  EyeOff,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Component = REGISTRY[name] ?? Minus;
  return <Component className={className} aria-hidden />;
}
